Repository oravirt/ansible-oracle, pull requests merged in 2022-11, with the labels that each got.

#291 Support to upgrade the timezone of the database
  changelogs/fragments/db_timezone_upgrade_support.yml
  roles/oradb_tzupgrade/README.md
  roles/oradb_tzupgrade/defaults/main.yml
  roles/oradb_tzupgrade/meta/main.yml
  roles/oradb_tzupgrade/tasks/cdb.yml
  roles/oradb_tzupgrade/tasks/main.yml
  roles/oradb_tzupgrade/tasks/non_cdb.yml
  roles/oradb_tzupgrade/tasks/tzpatch_db.yml
  roles/oradb_tzupgrade/vars/main.yml
Labels: enhancement

#294 Fix oracle export environment variables
  changelogs/fragments/manage_oracle_rdbms_procs.yml
  roles/oraswdb_install/files/manage_oracle_rdbms_procs.sh
Labels: bug

#296 Make some of the j2 templates source configurable
  changelogs/fragments/custom_template_path.yml
  roles/common/defaults/main.yml
  roles/common/tasks/main.yml
  roles/orahost/defaults/main.yml
  roles/orahost/tasks/main.yml
  roles/oraswdb_install/defaults/main.yml
  roles/oraswdb_install/tasks/install-home-db.yml
Labels: enhancement, question

#299 Documentation: Added feauturelist and missing picture
  README.adoc
  changelogs/fragments/299-doc.yml
  doc/chocolatey.puml
  doc/feauturelist.adoc
  doc/vagrant.adoc
Labels: enhancement

#300 oradb_manage_db: support for dbca custom scripts
  changelogs/fragments/customscripts_support.yml
  roles/oradb_manage_db/tasks/manage-db.yml
Labels: enhancement

#301 Replace include with include_tasks due to deprecation warning
  changelogs/fragments/301-include.yml
  roles/orahost/tasks/main.yml
  roles/orahost_ssh/tasks/main.yml
  roles/orahost_storage/tasks/main.yml
  roles/oraswdb_manage_patches/tasks/db-home-patch.yml
  roles/oraswgi_manage_patches/tasks/main.yml
Labels: bug

#302 oraasm_manage_diskgroups: Added support for ASMFD
  changelogs/fragments/302-oraasm_manage_diskgroups.yml
  roles/oraasm_manage_diskgroups/defaults/main.yml
Labels: bug, enhancement

#303 include_tasks: typo
  changelogs/fragments/301-include.yml
  roles/orahost/tasks/main.yml
  roles/orahost_ssh/tasks/main.yml
  roles/orahost_storage/tasks/main.yml
Labels: bug

#305 Update ocenv to 2022-11-22
  changelogs/fragments/305-ocenv.yml
  roles/oradb_manage_db/files/ocenv
Labels: bug, enhancement

#306 fix refactoring bug
  changelogs/fragments/128-oradb_manage_grants.yml
  roles/oradb_manage_grants/tasks/main.yml
Labels: bug
